version: '3'

services:

    solr:
        image: solr:8
        volumes:
            - ./solrCoreConfigurations/data:/var/solr/data/
        ports:
            - "8983:8983"
        command: solr-foreground
        entrypoint: "docker-entrypoint.sh"
        restart: always

#
#    sftp:
#        image: atmoz/sftp
#        volumes:
#            - ./ftpdata:/home/pep/upload
#        restart: always
#        ports:
#            - "2222:22"
#        command: pep:$$1$$xBD5VtwX$$wbyeEB9mJSD3j5yqyamHA0:e:1001
#        #  the password in encrypted, but this is still not the best way

#    ftp:
#      image: stilliard/pure-ftpd:hardened
#      ports:
#        - "21:21"
#        - "30000-30009:30000-30009"
#      volumes:
#        - ./ftpdata:/home/pep/
#        - ./config/ftp.passwd:/etc/pure-ftpd/pureftpd.passwd
#      environment:
#        PUBLICHOST: "localhost"
##        FTP_USER_NAME: pep
##        FTP_USER_PASS: NewPepPasswordIn2019
#        FTP_USER_HOME: /home/pep/
#      restart: always

    python2:
        build: solrXMLWebLoad
#        command: python
#        restart: always
#        please note that at the moment this does nothing

    python3.7:
        build: ./python3.7
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.7


    mysql:
        image: mysql:latest
        restart: always
        environment:
          MYSQL_DATABASE: 'opascentral'
          # So you don't have to use root, but you can if you like
          MYSQL_USER: 'pep_user'
          # You can use whatever password you like
          MYSQL_PASSWORD: 'peppass2'
          # Password for root access
          MYSQL_ROOT_PASSWORD: 'peppypeppep'
        ports:
          # <Port exposed> : < MySQL Port running inside container>
          - '3308:3306'
        expose:
          # Opens port 3306 on the container
          - '3308'
          # Where our data will be persisted
        volumes:
          - ./my-db:/var/lib/mysql
#
#
#

#volumes:
#    datavolume:
#        driver: local
#        driver_opts:
#            type: bind
#            device: ./mysql-data

#    solrdata:
#        driver: local
#        driver_opts:
#            type: bind
#            device: ./solrCoreConfigurations/data
