version: '3'

services:

    solr:
        image: solr:8
        volumes:
            - ./solrCoreConfigurations/data:/var/solr/data/
        ports:
            - "8983:8983"
        command: solr-foreground
        entrypoint: "docker-entrypoint.sh"
        restart: always

    python3.7:
        build: ./python3.7
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.7


    mysql:
        image: mysql:latest
        restart: always
        environment:
          MYSQL_DATABASE: 'opascentral'
          # So you don't have to use root, but you can if you like
          MYSQL_USER: 'pep_user'
          # You can use whatever password you like
          MYSQL_PASSWORD: 'peppass2'
          # Password for root access
          MYSQL_ROOT_PASSWORD: 'peppypeppep'
        ports:
          # <Port exposed> : < MySQL Port running inside container>
          - '3308:3306'
        expose:
          # Opens port 3306 on the container
          - '3308'
          # Where our data will be persisted
        volumes:
          - ./my-db:/var/lib/mysql
#
#
#

#volumes:
#    datavolume:
#        driver: local
#        driver_opts:
#            type: bind
#            device: ./mysql-data

#    solrdata:
#        driver: local
#        driver_opts:
#            type: bind
#            device: ./solrCoreConfigurations/data
