solr:
    image: solr:8
    volumes:
        - ./solrCoreConfigurations/data:/var/solr/data/
    ports:
        - "8983:8983"
    command: solr-foreground
    entrypoint: "docker-entrypoint.sh"
    restart: always
