sftp:
    image: atmoz/sftp
    volumes:
        - ./ftpdata:/home/foo/upload
    ports:
        - "2222:22"
    command: foo:pass:1001

solr:
    image: solr:8
    volumes:
        - ./solrCoreConfigurations/data:/var/solr/data/
    ports:
        - "8983:8983"
    command: solr-foreground
    entrypoint: "docker-entrypoint.sh"
    