version: '3.3'
services:
  solr:
      image: solr:latest
      environment:
          SOLR_JAVA_MEM: "-Xms1g -Xmx1g"
      volumes:
          - ./solrCoreConfigurations/data:/var/solr/data/
      ports:
          - "8983:8983"
      command: solr-foreground
      entrypoint: "docker-entrypoint.sh"
      restart: always


# Names our volume
volumes:
  solrdata:
      driver: local
      driver_opts:
          type: bind
          device: ./solrCoreConfigurations/data

