name: Plan and deploy OPAS to staging

on:
  pull_request:
    branches:
      - Stage

concurrency:
  group: ${{ github.ref }}-deploy
  cancel-in-progress: true

jobs:
  env:
    name: "Setup dynamic environment variables"
    runs-on: ubuntu-latest
    environment: staging-vars
    outputs:
      aws_account_id: ${{ steps.set-outputs.outputs.aws_account_id}}
    steps:
      - name: Set output
        id: set-outputs
        run: |
          echo "aws_account_id=${{ vars.AWS_ACCOUNT_ID }}" >> $GITHUB_OUTPUT
          echo "engineer_ips=${{ vars.ENGINEER_IPS }}" >> $GITHUB_OUTPUT

  infrastructure:
    needs: [env]
    uses: jordanallen-dev/reusable-terraform-workflow/.github/workflows/terraform.yml@main
    with:
      module-path: infra/staging
      apply-environment: staging
      s3-cache-bucket: pep-terraform-build-cache
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENV_VARS: "TF_VAR_account_id=${{ needs.env.outputs.aws_account_id }}\n\
        TF_VAR_mysql_username=${{ secrets.MYSQL_USERNAME }}\n\
        TF_VAR_mysql_password=${{ secrets.MYSQL_PASSWORD }}\n\
        TF_VAR_engineer_ips=${{ needs.env.outputs.engineer_ips }}\n\"